name: Deploy Frontend via AWS SSM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1  # Cambia esto si usas otra región (us-west-2, etc.)

    - name: Ejecutar Despliegue en EC2 vía SSM
      run: |
        aws ssm send-command \
          --instance-ids "${{ secrets.INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --comment "Desplegando la aplicación Frontend mediante GitHub Actions" \
          --parameters 'commands=[
            "mkdir -p ~/frontend-app",
            "cd ~/frontend-app",
            "git config --global --add safe.directory ~/frontend-app",
            "if [ ! -d \".git\" ]; then git clone https://github.com/${{ github.repository }}.git .; else git pull origin main; fi",
            "docker build -t frontend-innovatech .",
            "docker stop container-frontend || true",
            "docker rm container-frontend || true",
            "docker run -d --name container-frontend -p 80:80 frontend-innovatech"
          ]' \
          --output text